# Generated by Django 3.0.7 on 2020-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_message', models.CharField(max_length=50, verbose_name='İsim')),
                ('email_message', models.CharField(max_length=100, verbose_name='Eposta')),
                ('phone_message', models.CharField(max_length=10, verbose_name='Telefon')),
                ('content_message', models.CharField(max_length=200, verbose_name='İçerik')),
                ('date_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
